apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1po8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1po8
    app.kubernetes.io/part-of: cin4s-839-0090-app
  name: devfile-sample-1po8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1po8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1po8
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0090-tenant/cin4s-839-0090-app/devfile-sample-1po8@sha256:108588194d6a9b23cc9fed0201e4c0df889f761beb0e7ae4663f1193ab43504a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
